language: php

services:
  - docker

env:
  global:
    - PHP_COMPOSER_TAG="8.1-v2"
    - PHP_LARAVEL_TAG="8.1-fpm-v3"

php:
  - 8.1

before_script:
  # Upgrade Docker to the latest version
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update -y
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce
  - docker --version

  # Increase memory limit & disable xdebug for speed improvements
  - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - phpenv config-rm xdebug.ini

  # Authenticate Docker Hub
#  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin

script:
  - composer build

after_script:
  - docker images -a --filter='dangling=false' --format '{{.Repository}}:{{.Tag}}\t{{.Size}}'