name: Docker Builds

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.3]
                composer-script: [build, build-dev]

        name: PHP ${{ matrix.php }} - ${{ matrix.composer-script }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Build Docker Images
                run: composer ${{ matrix.composer-script }}
