name: Deploy to AWS EB

on:
    push:
    release:
        types: [published]

jobs:
    push:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.1]

        name: Docker Push

        steps:
          -   name: Checkout code
              uses: actions/checkout@v1

          -   name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

          -   name: Authenticate Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          -   name: Build Production Docker Image
              run: composer build

          -   name: Push Production Docker Image
              run: composer push

    deploy:
        needs: push
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.1]

        name: AWS EB Deploy

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Set Version
                run: echo "VERSION=$(echo $(head -n 1 version.txt) | cut -c 1-6)" >> $GITHUB_ENV

            -   name: Generate deployment package
                run: zip -r "${VERSION}".zip 'docker-compose.yml'

            -   name: Deploy to Elastic Beanstaalk
                uses: einaregilsson/beanstalk-deploy@v20
                with:
                    aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                    aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                    application_name: laravel-boilerplate
                    environment_name: laravel-boilerplate-web-production
                    version_label: ${{ env.VERSION }}
                    region: us-east-1
                    deployment_package: ${{ env.VERSION }}.zip
