name: Docker Push

on:
    release:
        types: [published]

jobs:
    deploy:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.1]

        name: PHP${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: 17
                    cache: 'yarn'

            -   name: Install Dependencies
                run: yarn install

            -   name: Build Webpacks
                run: yarn run production

            -   name: Build Production Docker Image
                run: bash .github/scripts/build-git.sh

            -   name: Push Production Docker Image
                run: bash .github/scripts/push-git.sh
