name: Test Suite

on:
    push:
        branches:
            - master
    pull_request:
    release:
        types: [published]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.3]
                composer-script: [boot-db-test]

        name: PHP ${{ matrix.php }} - ${{ matrix.composer-script }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Authenticate Docker Hub
                run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            -   name: Build Docker Images
                run: docker compose -f docker-compose-dev-db.yml build

            -   name: Pull Docker Images
                run: docker compose -f docker-compose-tests.yml pull --ignore-pull-failures

            -   name: Start Docker Services
                run: composer boot-db-test-start

            -   name: Migrate & seed database
                run: docker exec app php artisan migrate --seed

            -   name: Test application
                run: docker exec app ./vendor/bin/phpunit --testdox
