name: Test Suite

on:
    push:
        branches:
            - master
    pull_request:
    release:
        types: [published]

jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.3]
                composer-script: [boot-db-test]

        name: PHP ${{ matrix.php }} - ${{ matrix.composer-script }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Build Docker Images
                run: docker compose -f docker-compose-dev-db.yml build

            -   name: Pull Docker Images
                run: docker compose pull --ignore-pull-failures

            -   name: Test Docker Services
                run: composer ${{ matrix.composer-script }}
