name: Webpacks

on:
    pull_request:

jobs:
    yarn:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [21]
                environment: [development, production]

        name: Yarn ${{ matrix.node }} - ${{ matrix.environment }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4

            -   name: Setup node
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node }}
                    cache: 'yarn'

            -   name: Install Dependencies
                run: yarn install

            -   name: Build Webpacks
                run: yarn run ${{ matrix.environment }}

    webpack:
        needs: yarn
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ ubuntu-latest ]
                node: [ 21 ]
                environment: [ production ]

        permissions:
            # Give the default GITHUB_TOKEN write permission to commit and push the
            # added or changed files to the repository.
            contents: write

        name: Webpack ${{ matrix.node }} - ${{ matrix.environment }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.head_ref }}

            -   name: Setup node
                uses: actions/setup-node@v4
                with:
                    node-version: ${{ matrix.node }}
                    cache: 'yarn'

            -   name: Install Dependencies
                run: yarn install

            -   name: Build Webpacks
                run: yarn run ${{ matrix.environment }}

            -   uses: stefanzweifel/git-auto-commit-action@v6
                with:
                    commit_message: BUMP webpack builds to latest versions
                    status_options: '--untracked-files=no'
                    file_pattern: public/mix-manifest.json