name: Webpack Builds

on:
    push:
        branches-ignore:
            - 'master'
        paths:
            - '**.js'
            - '**.css?'
            - '**.blade.php'
            - 'resources/**'
            - 'public/**'
            - '**/package.json'
            - '**/yarn.lock'
            - '!public/**.json'

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                node: [17]
                environment: [production]

        name: Node ${{ matrix.node }} - ${{ matrix.environment }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
                with:
                    ref: ${{ github.head_ref }}
                    token: ${{ secrets.PAT }}

            -   name: Setup node
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node }}
                    cache: 'yarn'

            -   name: Install Dependencies
                run: yarn install

            -   name: Build Webpacks
                run: yarn run ${{ matrix.environment }}

            -   uses: stefanzweifel/git-auto-commit-action@v4
                with:
                    commit_message: BUMP webpack builds to latest versions
                    status_options: '--untracked-files=no'
                    file_pattern: public/mix-manifest.json
